config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'

  resources :cabins do #show index without log-in
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, except: [:new, :create, :index] do
    resources :reviews, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :cabin
  has_many :reviews, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  STATUSOPTIONS = ["accepted", "pending", "declined"]
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :number_of_guests, presence: true
  validates :location, presence: true
  validates :photo, presence: true
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :cabins, dependent: :destroy
  has_many :review, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    cabin = Cabin.find(params[:cabin_id])
    @booking.cabin = cabin

    if @booking.valid?
      @booking.save
      redirect_to profile_path
    else
      render 'cabins/show'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to profile_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to profile_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  def index
    @cabins = Cabin.all
    @markers = @cabins.geocoded.map do |cabin|
      {
        lat: cabin.latitude,
        lng: cabin.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { cabin: cabin })
      }
    end
  end

  def show
    @booking = Booking.new
    @cabin = Cabin.find(params[:id])
    @marker = { lat: @cabin.latitude,
                lng: @cabin.longitude }
  end

  def new
    @cabin = Cabin.new
  end

  def create
    @cabin = Cabin.new(strong_params)
    @cabin.user = current_user
    if @cabin.save
      redirect_to profile_path
    else
      render 'new'
    end
  end

  def edit
    @cabin = Cabin.find(params[:id])
  end

  def update
    @cabin = Cabin.find(params[:id])
    @cabin.update(strong_params)

    redirect_to profile_path
  end

  def destroy
    @cabin = Cabin.find(params[:id])
    @cabin.destroy

    redirect_to profile_path
  end

  private

  def strong_params
    params.require(:cabin).permit(:name, :description, :price_per_night, :number_of_guests, :location, :user, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @cabins = Cabin.all
    @selected_cabins = @cabins.first(9)
  end

  def profile
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.booking = Booking.find(params[:booking_id])
    if @review.save
      redirect_to cabins_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def cabins
    @cabins = @user.cabins
  end

  def bookings
    @bookings = @user.bookings
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 text-center">
      <h1>Edit your booking</h1>
      <h3>Current details:</h3>
      Start date: <%= @booking.start_date  %>
      <br>
      End date: <%= @booking.end_date  %>
      <br>
      Cabin: <%= @booking.cabin.name  %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-6">
      <h2>New dates:</h2>
      <%= simple_form_for [ @booking ] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit "Edit booking", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cabins/_cabin-index-cards.html.erb
<% @cabins.each do |cabin| %>
  <%= link_to cabin_path(cabin), class: "no-dec-link" do %>
  <div class="card-cabin-index" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url( <%= cabin.photo.attached? ? cl_image_path(cabin.photo.key) : "" %> );">
      <h4> <%= cabin.name %> </h4>
      <div class="cabin-index-show-text" >
        <i class="fas fa-users" style="color:white"> <%= cabin.number_of_guests %></i>
        <i class="fas fa-pound-sign" style="color:white"> <%= cabin.price_per_night %></i>
        <h5 style="color:white"><%= cabin.location %></h5>
      </div>
    </div>
    <p style="color:white"><%= cabin.location %></p>
  <% end %>
  
<% end %>

app/views/cabins/_info_window.html.erb
<h2><%= cabin.name %></h2>
<p><%= cabin.location %></p>
<p>£<%= cabin.price_per_night %>/night</p>

app/views/cabins/_review-cards.html.erb
<% @reviews.each do |review| %>
  <div class="review-card"></div>
    <h4> <%= "⭐️"*review.rating %> </h4>
    <p><%= review.content %></p>
<% end %>

app/views/cabins/edit.html.erb
<div class="container" >
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@cabin) do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price_per_night %>
        <%= f.input :number_of_guests %>
        <%= f.input :location %>
        <%= f.input :photo, as: :file %>
        <div class=“form-actions btn”>
          <%= f.button :submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cabins/index.html.erb
<div class="container">
  <div class="justify-content-center">
    <h2 style="color:#659B5E">Here are some of our cabins:</h2>
    <br>
    <div class="cards">
      <%= render 'cabin-index-cards' %>
    </div>
    <div id="map"
     style="width: 100%; height: 600px; margin: 30px 0;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/cabins/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for [ @cabin ] do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.input :location %>
      <%= f.input :photo, as: :file %>

      <%= f.submit "Create Cabin", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cabins/show.html.erb
<div class="container">
  <%= link_to cabins_path, class: 'btn back-link' do %>
    <i class="fas fa-angle-double-left"></i> Cabins
  <% end %>
  <div class="content-show">
    <div class="content-details">
      <div class="row justify-content-center">
        <div class="cabin-headers text-start">
          <h1> <%=  @cabin.name  %> </h1>
          <p> <%=  @cabin.description  %> </p>
          <img class="cabin-image" src= <%= cl_image_path @cabin.photo.key %> alt="">
        </div>
      </div>
    </div>

    <div class="content-booking">
      <div class="booking-form">
        <div class="row justify-content-center">
          <h3 class="text-center">Book Now</h3>
          <%= simple_form_for [@cabin, @booking] do |f| %>
          <%= f.input :start_date %>
          <%= f.input :end_date %>
          <%= f.submit "Make booking", class: "btn" %>
          <% end %>
        </div>
      </div>

      <br>
      <div class="cabin-show-text-single">
        <h5>Price per night: £<%=  @cabin.price_per_night  %> </h5>
        <h5>Maximum number of guests: <%= @cabin.number_of_guests  %> </h5>
      </div>

      <% if @cabin.reviews.count > 0 %>
        <div class="reviews-container">
          <h3>Reviews for <%=@cabin.name %>:</h3>
          <% @cabin.reviews.each do |review| %>
            <div class="review-card">
              <h4> <%= "⭐️"*review.rating %> </h4>
              <p><%= review.content %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div id="map-show"
    style="width: 100%; height: 400px; margin: 30px auto 30px auto;"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFlashAirbnbCabinClone</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css' rel='stylesheet' />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'shared/flashes' %>
  <% if !current_page?("/") %>
    <%= render 'shared/navbar' %>
  <% end %>
  <%= yield %>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/pages/_cabin-cards.html.erb
<% @selected_cabins.each do |cabin| %>
  <%= link_to cabin_path(cabin), class: "no-dec-link" do %>
    <div class="card-cabin-index" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url( <%= cl_image_path cabin.photo.key %> );">
      <h4> <%= cabin.name %> </h4>
      <div class="cabin-show-text" >
        <i class="fas fa-users" style="color:white"> <%= cabin.number_of_guests %></i>
        <i class="fas fa-pound-sign" style="color:white"> <%= cabin.price_per_night %></i>
        <h5 style="color:white"><%= cabin.location %></h5>
      </div>
    </div>
<% end %>
<% end %>

app/views/pages/_countries.html.erb
<div class="countries-card">
    <img src= "https://source.unsplash.com/1080x1080/?USA" class="card-img-top" alt="log cabin">
    <div class="card-body">
      <h4> USA </h4>
    </div>
</div>

<div class="countries-card">
    <img src= "https://source.unsplash.com/1080x1080/?UK" class="card-img-top" alt="log cabin">
    <div class="card-body">
      <h4> UK </h4>
    </div>
</div>

<div class="countries-card">
    <img src= "https://source.unsplash.com/1080x1080/?ireland" class="card-img-top" alt="log cabin">
    <div class="card-body">
      <h4> Ireland </h4>
    </div>
</div>

<div class="countries-card">
    <img src= "https://source.unsplash.com/1080x1080/?france" class="card-img-top" alt="log cabin">
    <div class="card-body">
      <h4> France </h4>
    </div>
</div>

<div class="countries-card">
    <img src= "https://source.unsplash.com/1080x1080/?italy" class="card-img-top" alt="log cabin">
    <div class="card-body">
      <h4> Italy </h4>
    </div>
</div>

<div class="countries-card">
    <img src= "https://source.unsplash.com/1080x1080/?iceland" class="card-img-top" alt="log cabin">
    <div class="card-body">
      <h4> Iceland </h4>
    </div>
</div>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner">
  <div class="navbar-home">
    <div class="navbar-logo">
      <% if !user_signed_in? %>
        <%= link_to "Login", new_user_session_path, class: "btn" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn" %>
      <% end %>
    </div>
    <div class="home-buttons">
      <div class="button-for-home">
      <%= link_to 'Host Your Cabin', new_cabin_path, class: "btn"  %>
      </div>

        <% if user_signed_in? %>
        <div class="button-for-home">
          <%= link_to "#{current_user.first_name}'s Profile", profile_path, class: "btn" %>
        </div>
        <% end %>
    </div>
  </div>
  <div class="content">
    <h1>Cabin-Bnb</h1>
    <%= link_to "Book A Cabin", cabins_path, class: "btn" , id:"book-a-cabin-button"%>
  </div>
</div>

<!-- Cabins -->
<h2>Top Rated Cabins</h2>
<div class="home-cabins-container">
  <div class="home-container">
    <div class="row">
      <div class="col">
        <div class="home-cards">
          <%= render 'cabin-cards' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <%= link_to cabins_path, class: 'btn back-link' do %>
    <i class="fas fa-angle-double-left"></i> All Cabins
  <% end %>

  <div class="profile-details">
    <% if !current_user.cabins.empty? %>
      <h4 class="header" style="color:#659B5E">Your Cabins:</h4>
      <br>
      <div class="cards">
        <% current_user.cabins.each do |cabin| %>
          <div class="card-profile">
            <% if cabin.photo.attached? %>
              <%= cl_image_tag cabin.photo.key, alt: "alttext" %>
            <% else %>
              <img src="https://images.pexels.com/photos/4947737/pexels-photo-4947737.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="">
            <% end %>
            <h5 style="color:#659B5E"><%= cabin.name %></h5>
            <br>
            <p><%= cabin.description %> </p>
            <span>
              <%= link_to 'Edit', edit_cabin_path(cabin), class: "btn" %>
              <%= link_to 'Delete', cabin_path(cabin), method: :delete, class: "btn" %>

              <h6 style="color:#659B5E"> Bookings </h6>
              <% cabin.bookings.each do |booking| %>
                <p><%=  booking.start_date %> - <%=  booking.end_date %></p>
                  <div class="booking-status">
                  <% if booking.status == false %>
                    <p>Status: Pending</p>
                  <% else %>
                    <p>Status: Accepted</p>
                  <% end %>

                  <% if booking.status != true %>
                    <%= simple_form_for [booking] do |f| %>
                      <%= f.input :status, as: :boolean, selected: false, label: "Accept" %>
                      <%= f.submit "Accept booking", class: "btn" %>
                    <% end %>
                  <% end %>
                  <%= link_to 'Delete Booking', booking_path(booking), method: :delete, class: "btn" %>
                  </div>
              <% end %>
            </span>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="profile-buttons-else">
        <p id="add-cabin-text">Looks like you've not listed any cabins on your profile... If you have a spare cabin you want to rent, list it here!</p>
        <%= link_to 'Host Your Cabin Today', new_cabin_path, class: "btn" %>
      </div>
    <% end %>
  </div>

  <div class="profile-details">
    <% if !current_user.bookings.empty? %>
      <h4 class="header" style="color:#659B5E">Your Upcoming Bookings:</h4>
      <br>
      <div class="cards">
        <% current_user.bookings.each do |booking| %>
          <div class="card-profile">
            <% if booking.cabin.photo.attached? %>
              <%= cl_image_tag booking.cabin.photo.key, alt: "alttext" %>
            <% else %>
              <img src="https://images.pexels.com/photos/4947737/pexels-photo-4947737.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="">
            <% end %>
            <h5><%= link_to booking.cabin.name, cabin_path(booking.cabin), class: "no-dec-profile-link" %> </h5>
            <br>
            <p><strong>From: </strong><%= booking.start_date.strftime("%B %d, %Y")%></p><p><strong>To: </strong><%= booking.end_date.strftime("%B %d, %Y") %></p>
            <p>Total Cost: £<%= (booking.end_date - booking.start_date).to_i * booking.cabin.price_per_night %> </p>
            <div class="profile-buttons">
              <%= link_to 'Edit', edit_booking_path(booking), class: "btn" %>
              <%= link_to 'Delete', booking_path(booking), method: :delete, class: "btn" %>
              <%= link_to 'Review', new_booking_review_path(booking), class: "btn" %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="profile-buttons-else">
        <p id="add-booking-text">Looks like you've not got any bookings... Let's change that!</p>
        <%= link_to 'Make a Booking', cabins_path, class: "btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>What did you think? </h1>

      <%= simple_form_for [ @booking, @review ] do |f| %>
      <%= f.input :content, placeholder: 'Your review' %>
      <%= f.input :rating, collection: 0..5 %>
      <%= f.submit "Leave Review", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="d-flex justify-content-around footer-basic">
  <footer class="footer-create">
   <div class="social d-flex justify-content-between">
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="https://github.com/JamesWordie/rails-flash-airbnb-cabin-clone"><i class="fab fa-github-square"></i></a>
    <a href="#"><i class="fab fa-twitter-square"></i></a>
  </div>
  <p class="fw-light text-black-50" >This website was made by James Wordie, Jonathan Simpson, Per Jensen & Matt Vile</p>
</footer>
</div>

app/views/shared/_navbar.html.erb
<header class="page-header">
<div class="navbar">
	<div class="navbar-logo">
    <%= link_to root_path do %>
      <i class='fas fa-home' id='home'></i>
    <% end %>
    <% if !user_signed_in? %>
      <%= link_to "Login", new_user_session_path, class: "btn" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn" %>
    <% end %>
<!-- 		<a class="navbar-brand" href="#">
			<img src="https://images.pexels.com/photos/2083465/pexels-photo-2083465.jpeg?cs=srgb&dl=pexels-louis-2083465.jpg&fm=jpg" class="rounded" width="60" height="60" alt="">
		</a> -->
	</div>
<!-- 	<div class="navbar-search-bar me-3">
		<div class="input-group">
			<input class="form-control form-control-lg border-end-0 border border-dark rounded-pill rounded-end" type="text" value="Start your search" id="example-search-input" />
			<span class="input-group-append">
				<button class="btn btn-outline-dark btn-lg border-start-0 rounded-pill rounded-start" type="button">
					<i class="fa fa-search"></i>
				</button>
			</span>
		</div>
	</div> -->
	<div class="dropdown">
    <%= link_to 'Host Your Cabin', new_cabin_path, class: "btn"  %>
      <% if user_signed_in? %>
    <%= link_to "#{current_user.first_name}'s Profile", profile_path, class: "btn" %>
  <% end %>
	</div>
</div>
</header>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">